<a href="https://colab.research.google.com/github/rani-sikdar/GenAI-complete-course-codes/blob/main/7_BOW_bag_of_words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd


In [2]:
file_ = '/content/spam_classifier_dataset.csv'

In [3]:
messages_df = pd.read_csv(file_)

In [4]:
messages_df['message']

0           Lunch was amazing today. We should go again!
1      Please review the attached document and share ...
2           Lunch was amazing today. We should go again!
3              Just checking in. How’s everything going?
4      Please review the attached document and share ...
                             ...                        
495       Happy birthday! Hope you have a wonderful day.
496    Meeting rescheduled to 3 PM. Let me know if th...
497    Meeting rescheduled to 3 PM. Let me know if th...
498    FREE entry in 2 a weekly competition to win an...
499         I’ll be late to the party, stuck in traffic.
Name: message, Length: 500, dtype: object

In [5]:
# data cleaning and preprocessing

import nltk
import re

In [6]:
nltk.download('english')

[nltk_data] Error loading english: Package 'english' not found in
[nltk_data]     index


False

In [7]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

porter_stemming = PorterStemmer()

In [8]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [9]:
corpus =list()

for i in range(len(messages_df)):
  sentences = re.sub('[^a-zA-z]', ' ', messages_df['message'][i])
  # print(sentences)

  sentences = sentences.lower().split()
  sentences = [porter_stemming.stem(word) for word in sentences if word not in set(stopwords.words('english'))]
  sentences = ' '.join(sentences)
  corpus.append(sentences)

In [10]:
corpus

['lunch amaz today go',
 'pleas review attach document share feedback',
 'lunch amaz today go',
 'check everyth go',
 'pleas review attach document share feedback',
 'hey still meet coffe tomorrow',
 'hey still meet coffe tomorrow',
 'get rich quick earn week home limit time offer',
 'check everyth go',
 'happi birthday hope wonder day',
 'happi birthday hope wonder day',
 'pleas review attach document share feedback',
 'get rich quick earn week home limit time offer',
 'lunch amaz today go',
 'lunch amaz today go',
 'get credit score boost instantli sign',
 'free entri weekli competit win ipad text win',
 'happi birthday hope wonder day',
 'check everyth go',
 'late parti stuck traffic',
 'get credit score boost instantli sign',
 'great time concert last night',
 'great time concert last night',
 'hey still meet coffe tomorrow',
 'get credit score boost instantli sign',
 'lunch amaz today go',
 'late parti stuck traffic',
 'lunch amaz today go',
 'urgent lotteri contact us receiv',
 '

In [12]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv = CountVectorizer(max_features=100,binary=True) # binary ====> binary bow

In [13]:
X = cv.fit_transform(corpus).toarray()

In [14]:
X

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
X.shape

(500, 94)

In [20]:
cv = CountVectorizer(max_features=500,binary=False) # binary ====> binary bow

In [21]:
X = cv.fit_transform(corpus).toarray()

In [22]:
X

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 2, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
X.shape

(500, 94)

In [24]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x))
X

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..., 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..., 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [25]:
cv.vocabulary_

{'lunch': np.int64(54),
 'amaz': np.int64(2),
 'today': np.int64(81),
 'go': np.int64(36),
 'pleas': np.int64(60),
 'review': np.int64(66),
 'attach': np.int64(4),
 'document': np.int64(24),
 'share': np.int64(72),
 'feedback': np.int64(30),
 'check': np.int64(11),
 'everyth': np.int64(27),
 'hey': np.int64(39),
 'still': np.int64(75),
 'meet': np.int64(55),
 'coffe': np.int64(14),
 'tomorrow': np.int64(82),
 'get': np.int64(34),
 'rich': np.int64(67),
 'quick': np.int64(62),
 'earn': np.int64(25),
 'week': np.int64(89),
 'home': np.int64(41),
 'limit': np.int64(52),
 'time': np.int64(80),
 'offer': np.int64(57),
 'happi': np.int64(38),
 'birthday': np.int64(7),
 'hope': np.int64(42),
 'wonder': np.int64(92),
 'day': np.int64(20),
 'credit': np.int64(19),
 'score': np.int64(69),
 'boost': np.int64(8),
 'instantli': np.int64(45),
 'sign': np.int64(73),
 'free': np.int64(33),
 'entri': np.int64(26),
 'weekli': np.int64(90),
 'competit': np.int64(15),
 'win': np.int64(91),
 'ipad': np.int

In [28]:
## Create the Bag OF Words model with ngram

from sklearn.feature_extraction.text import CountVectorizer

## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=100,binary=True,ngram_range=(2,3)) # ngram_range =(2,3) ---> means bigrams and trigrams
X=cv.fit_transform(corpus).toarray()

In [29]:
cv.vocabulary_

{'lunch amaz': np.int64(59),
 'amaz today': np.int64(1),
 'today go': np.int64(94),
 'lunch amaz today': np.int64(60),
 'amaz today go': np.int64(2),
 'pleas review': np.int64(71),
 'review attach': np.int64(79),
 'attach document': np.int64(4),
 'document share': np.int64(24),
 'share feedback': np.int64(85),
 'pleas review attach': np.int64(72),
 'review attach document': np.int64(80),
 'attach document share': np.int64(5),
 'document share feedback': np.int64(25),
 'check everyth': np.int64(12),
 'everyth go': np.int64(28),
 'check everyth go': np.int64(13),
 'hey still': np.int64(45),
 'still meet': np.int64(86),
 'meet coffe': np.int64(61),
 'coffe tomorrow': np.int64(15),
 'hey still meet': np.int64(46),
 'still meet coffe': np.int64(87),
 'meet coffe tomorrow': np.int64(62),
 'happi birthday': np.int64(43),
 'birthday hope': np.int64(8),
 'hope wonder': np.int64(47),
 'wonder day': np.int64(99),
 'happi birthday hope': np.int64(44),
 'birthday hope wonder': np.int64(9),
 'hope w

In [30]:
X

array([[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, ..., 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, ..., 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0